# -*- coding: utf-8 -*-
"""01_non_personalized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GL2OX86i-YdRDWrblRxJyTyt_gi9aagU
"""

# 01_non_personalized.ipynb

## 0. Contributors
## 1. Objective
## 2. Imports and Data Loading
## 3. Data Preparation
## 4. Exploratory Data Analysis
## 5. Train/Test Split
## 6. Non-personalized recommenders
## 7. Evaluation

"""#**0. Contributors**
- Jacobo Galindo Sanz

#**1. Objective**

The objective of this notebook is to implement non-personalized recommendation models as baseline approaches to establish a reference point for evaluating more advanced techniques. These models do not incorporate individual user preferences but instead rely on global patterns observed in the dataset.

#**2. Imports and Data Loading**
"""

#Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 140)

#Data loading
orders = pd.read_csv("orders.csv")
order_products_prior = pd.read_csv("order_products__prior.csv")
products = pd.read_csv("products.csv")
aisles = pd.read_csv("aisles.csv")
departments = pd.read_csv("departments.csv")

#Size of datasets
for name, df in [
    ("orders", orders),
    ("order_products_prior", order_products_prior),
    ("products", products),
    ("aisles", aisles),
    ("departments", departments),
]:
    print(f"{name}: {df.shape}")

"""#**3. Data Preparation**

"""

#Merge: products with aisle and department
products_full = (
    products
    .merge(aisles, on="aisle_id", how="left")
    .merge(departments, on="department_id", how="left")
)

products_full.head()

#Merge: prior orders with orders and products
prior = (
    order_products_prior
    .merge(orders, on="order_id", how="left")
    .merge(products_full, on="product_id", how="left")
)

prior.head()

#Check columns
print(prior.columns.tolist())

"""#**4. Exploratory Data Analysis**

"""

#Size of the problem
n_users = prior["user_id"].nunique()
n_products = prior["product_id"].nunique()
n_orders = prior["order_id"].nunique()
n_interactions = len(prior)

print("Users:", n_users)
print("Products:", n_products)
print("Orders:", n_orders)
print("Interactions:", n_interactions)

#Sparsity
sparsity = 1 - (n_interactions / (n_users * n_products))
print(f"Sparsity: {sparsity:.2%}")

#Top products
top_products = (
    prior.groupby(["product_id", "product_name"])
    .size()
    .reset_index(name="purchase_count")
    .sort_values("purchase_count", ascending=False)
    .head(15)
)

top_products

plt.figure(figsize=(10, 5))
plt.barh(top_products["product_name"][::-1], top_products["purchase_count"][::-1])
plt.title("Top 15 Most Purchased Products")
plt.xlabel("Number of Purchases")
plt.ylabel("Product")
plt.tight_layout()
plt.show()

#Purchases per user
user_activity = prior.groupby("user_id").size()

print(user_activity.describe())

plt.figure(figsize=(8, 4))
plt.hist(user_activity, bins=50)
plt.title("Purchases per User")
plt.xlabel("Number of Purchased Items")
plt.ylabel("Number of Users")
plt.tight_layout()
plt.show()

#Product popularity
product_popularity = prior.groupby("product_id").size()

print(product_popularity.describe())

plt.figure(figsize=(8, 4))
plt.hist(product_popularity, bins=50)
plt.yscale("log")
plt.title("Product Popularity Distribution")
plt.xlabel("Number of Purchases")
plt.ylabel("Number of Products (log scale)")
plt.tight_layout()
plt.show()

#Reorder rate
print("Global reorder rate:", prior["reordered"].mean())

"""#**5. Train/Test Split**

"""

# --- SAFE SPLIT BLOCK (can be re-run multiple times) ---

# Work on a clean copy to avoid merge issues
prior_split = prior.copy()

# Remove column if it already exists (prevents merge error)
if "last_order_number" in prior_split.columns:
    prior_split = prior_split.drop(columns=["last_order_number"])

# Last order per user
user_last_order = (
    prior_split.groupby("user_id")["order_number"]
    .max()
    .reset_index()
)

user_last_order.columns = ["user_id", "last_order_number"]

# Merge safely
prior_split = prior_split.merge(user_last_order, on="user_id", how="left")

# Train / Test split
train_df = prior_split[prior_split["order_number"] < prior_split["last_order_number"]].copy()
test_df = prior_split[prior_split["order_number"] == prior_split["last_order_number"]].copy()

# Keep only users present in train
valid_users = train_df["user_id"].unique()
test_df = test_df[test_df["user_id"].isin(valid_users)].copy()

# Keep only users present in both train and test (clean evaluation)
train_users = set(train_df["user_id"].unique())
test_users = set(test_df["user_id"].unique())
common_users = train_users.intersection(test_users)

train_df = train_df[train_df["user_id"].isin(common_users)].copy()
test_df = test_df[test_df["user_id"].isin(common_users)].copy()

# Print stats
print("Train interactions:", len(train_df))
print("Test interactions:", len(test_df))
print("Train users:", train_df["user_id"].nunique())
print("Test users:", test_df["user_id"].nunique())

# Ground truth per user
ground_truth = (
    test_df.groupby("user_id")["product_id"]
    .apply(set)
    .to_dict()
)

print("Users in ground truth:", len(ground_truth))

"""#**6. Non-Personalized Recommenders**

###**6.1 Most popular (basic baseline)**
"""

# Global popularity
global_popularity = (
    train_df.groupby(["product_id", "product_name"])
    .size()
    .reset_index(name="purchase_count")
    .sort_values("purchase_count", ascending=False)
)

global_popularity.head(10)

# Recommendation list
popular_products = global_popularity["product_id"].tolist()

def recommend_most_popular(k=10):
    return popular_products[:k]

"""###**6.2 Top Reorder Rate**

"""

reorder_stats = (
    train_df.groupby(["product_id", "product_name"])
    .agg(
        reorder_rate=("reordered", "mean"),
        purchase_count=("product_id", "count")
    )
    .reset_index()
)

# Combine both signals
reorder_stats["score"] = (
    reorder_stats["reorder_rate"] *
    np.log1p(reorder_stats["purchase_count"])
)

reorder_stats = reorder_stats.sort_values("score", ascending=False)

reorder_stats.head(10)

top_reorder_products = reorder_stats["product_id"].tolist()

def recommend_top_reorder(k=10):
    return top_reorder_products[:k]

"""###**6.3 Weighted Reorder Score**

"""

# 6.3 Bayesian Weighted Reorder Score

# Step 1: Compute product-level stats
bayesian_stats = (
    train_df.groupby(["product_id", "product_name"])
    .agg(
        purchase_count=("product_id", "count"),
        reorder_rate=("reordered", "mean")
    )
    .reset_index()
)

# Step 2: Global average reorder rate across all products
C = bayesian_stats["reorder_rate"].mean()

# Step 3: Minimum votes / confidence threshold
# Good practice: use a percentile of purchase counts
m = bayesian_stats["purchase_count"].quantile(0.9)

print(f"Global average reorder rate (C): {C:.4f}")
print(f"Minimum purchase threshold (m): {m:.0f}")

# Step 4: Bayesian weighted score
bayesian_stats["bayesian_score"] = (
    (bayesian_stats["purchase_count"] / (bayesian_stats["purchase_count"] + m)) * bayesian_stats["reorder_rate"]
    + (m / (bayesian_stats["purchase_count"] + m)) * C
)

# Step 5: Rank products
bayesian_stats = bayesian_stats.sort_values("bayesian_score", ascending=False)

# Show top results
bayesian_stats.head(10)

top_bayesian_products = bayesian_stats["product_id"].tolist()

def recommend_bayesian(k=10):
    return top_bayesian_products[:k]

"""#**7. Evaluation**

"""

import math
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import csr_matrix

#Metric Functions

def precision_at_k(recommended, relevant, k=10):
    recommended = recommended[:k]
    if k == 0:
        return 0.0
    return len(set(recommended) & set(relevant)) / k

def recall_at_k(recommended, relevant, k=10):
    recommended = recommended[:k]
    if len(relevant) == 0:
        return 0.0
    return len(set(recommended) & set(relevant)) / len(set(relevant))

def ndcg_at_k(recommended, relevant, k=10):
    recommended = recommended[:k]
    dcg = 0.0
    for idx, item in enumerate(recommended, start=1):
        if item in relevant:
            dcg += 1 / math.log2(idx + 1)

    ideal_hits = min(len(set(relevant)), k)
    if ideal_hits == 0:
        return 0.0

    idcg = sum(1 / math.log2(i + 1) for i in range(1, ideal_hits + 1))
    return dcg / idcg

def coverage_at_k(all_recommendations, catalog_size, k=10):
    recommended_items = set()
    for recs in all_recommendations.values():
        recommended_items.update(recs[:k])
    return len(recommended_items) / catalog_size if catalog_size > 0 else 0.0

def intra_list_diversity(recommended, similarity_dict, k=10):
    items = recommended[:k]
    if len(items) < 2:
        return 0.0

    pairwise_sims = []
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            sim = similarity_dict.get((items[i], items[j]), similarity_dict.get((items[j], items[i]), 0.0))
            pairwise_sims.append(sim)

    if len(pairwise_sims) == 0:
        return 0.0

    return 1 - np.mean(pairwise_sims)

def serendipity_at_k(recommended, relevant, popular_set, k=10):
    recommended = recommended[:k]
    hits = [item for item in recommended if item in relevant and item not in popular_set]
    return len(hits) / k if k > 0 else 0.0

# Score dictionaries (needed for RMSE)

pop_score_dict = dict(zip(global_popularity["product_id"], global_popularity["purchase_count"] / global_popularity["purchase_count"].max()))

reorder_score_dict = dict(zip(reorder_stats["product_id"], reorder_stats["score"]))

bayesian_score_dict = dict(zip(bayesian_stats["product_id"], bayesian_stats["bayesian_score"]))

# RMSE / MAE Evaluation on Test Set

test_eval = test_df.copy()

test_eval["pred_pop"] = test_eval["product_id"].map(pop_score_dict).fillna(0)
test_eval["pred_reorder"] = test_eval["product_id"].map(reorder_score_dict).fillna(0)
test_eval["pred_bayesian"] = test_eval["product_id"].map(bayesian_score_dict).fillna(0)

y_true = test_eval["reordered"]

rmse_pop = np.sqrt(mean_squared_error(y_true, test_eval["pred_pop"]))
mae_pop = mean_absolute_error(y_true, test_eval["pred_pop"])

rmse_reorder = np.sqrt(mean_squared_error(y_true, test_eval["pred_reorder"]))
mae_reorder = mean_absolute_error(y_true, test_eval["pred_reorder"])

rmse_bayesian = np.sqrt(mean_squared_error(y_true, test_eval["pred_bayesian"]))
mae_bayesian = mean_absolute_error(y_true, test_eval["pred_bayesian"])

print("Most Popular     -> RMSE:", round(rmse_pop, 4), "| MAE:", round(mae_pop, 4))
print("Top Reorder Rate -> RMSE:", round(rmse_reorder, 4), "| MAE:", round(mae_reorder, 4))
print("Weighted Score   -> RMSE:", round(rmse_bayesian, 4), "| MAE:", round(mae_bayesian, 4))

# User Evaluation

K = 10
results = []

all_recs_pop = {}
all_recs_reorder = {}
all_recs_bayesian = {}

for user_id, relevant_items in ground_truth.items():
    rec_pop = recommend_most_popular(k=K)
    rec_reorder = recommend_top_reorder(k=K)
    rec_bayesian = recommend_bayesian(k=K)

    all_recs_pop[user_id] = rec_pop
    all_recs_reorder[user_id] = rec_reorder
    all_recs_bayesian[user_id] = rec_bayesian

    results.append({
        "user_id": user_id,

        "precision_pop": precision_at_k(rec_pop, relevant_items, K),
        "recall_pop": recall_at_k(rec_pop, relevant_items, K),
        "ndcg_pop": ndcg_at_k(rec_pop, relevant_items, K),

        "precision_reorder": precision_at_k(rec_reorder, relevant_items, K),
        "recall_reorder": recall_at_k(rec_reorder, relevant_items, K),
        "ndcg_reorder": ndcg_at_k(rec_reorder, relevant_items, K),

        "precision_bayesian": precision_at_k(rec_bayesian, relevant_items, K),
        "recall_bayesian": recall_at_k(rec_bayesian, relevant_items, K),
        "ndcg_bayesian": ndcg_at_k(rec_bayesian, relevant_items, K),
    })

results_df = pd.DataFrame(results)
results_df.head()

#Lightweight diversity using metadata

product_meta = (
    products_full[["product_id", "aisle_id", "department_id"]]
    .drop_duplicates()
    .set_index("product_id")
)

def metadata_diversity_at_k(recommended, product_meta, k=10):
    items = recommended[:k]

    if len(items) < 2:
        return 0.0

    valid_items = [item for item in items if item in product_meta.index]

    if len(valid_items) < 2:
        return 0.0

    pair_scores = []

    for i in range(len(valid_items)):
        for j in range(i + 1, len(valid_items)):
            item_i = valid_items[i]
            item_j = valid_items[j]

            same_aisle = (
                product_meta.loc[item_i, "aisle_id"] ==
                product_meta.loc[item_j, "aisle_id"]
            )

            same_department = (
                product_meta.loc[item_i, "department_id"] ==
                product_meta.loc[item_j, "department_id"]
            )

            # similarity proxy:
            # 1.0 if same aisle
            # 0.5 if same department but different aisle
            # 0.0 if different department
            if same_aisle:
                sim = 1.0
            elif same_department:
                sim = 0.5
            else:
                sim = 0.0

            pair_scores.append(sim)

    if len(pair_scores) == 0:
        return 0.0

    return 1 - np.mean(pair_scores)

#Popular Set for Serendipity

popular_set = set(global_popularity["product_id"].head(20).tolist())
popular_set

# Diversity and Serendipity
diversity_pop = np.mean([
    metadata_diversity_at_k(recs, product_meta, K)
    for recs in all_recs_pop.values()
])

diversity_reorder = np.mean([
    metadata_diversity_at_k(recs, product_meta, K)
    for recs in all_recs_reorder.values()
])

diversity_bayesian = np.mean([
    metadata_diversity_at_k(recs, product_meta, K)
    for recs in all_recs_bayesian.values()
])

serendipity_pop = np.mean([
    serendipity_at_k(all_recs_pop[user_id], ground_truth[user_id], popular_set, K)
    for user_id in ground_truth
])

serendipity_reorder = np.mean([
    serendipity_at_k(all_recs_reorder[user_id], ground_truth[user_id], popular_set, K)
    for user_id in ground_truth
])

serendipity_bayesian = np.mean([
    serendipity_at_k(all_recs_bayesian[user_id], ground_truth[user_id], popular_set, K)
    for user_id in ground_truth
])

print("Diversity - Most Popular:", round(diversity_pop, 4))
print("Diversity - Top Reorder:", round(diversity_reorder, 4))
print("Diversity - Weighted Score:", round(diversity_bayesian, 4))

print("Serendipity - Most Popular:", round(serendipity_pop, 4))
print("Serendipity - Top Reorder:", round(serendipity_reorder, 4))
print("Serendipity - Weighted Score:", round(serendipity_bayesian, 4))
print("Serendipity - Weighted Score:", round(serendipity_bayesian, 4))

#Coverage

catalog_size = train_df["product_id"].nunique()

coverage_pop = coverage_at_k(all_recs_pop, catalog_size, K)
coverage_reorder = coverage_at_k(all_recs_reorder, catalog_size, K)
coverage_bayesian = coverage_at_k(all_recs_bayesian, catalog_size, K)

print("Coverage - Most Popular:", round(coverage_pop, 4))
print("Coverage - Top Reorder:", round(coverage_reorder, 4))
print("Coverage - Weighted Score:", round(coverage_bayesian, 4))

#Final Comparison Table

comparison_table = pd.DataFrame([
    {
        "Approach": "Most Popular",
        "RMSE": rmse_pop,
        "MAE": mae_pop,
        "Precision@K": results_df["precision_pop"].mean(),
        "Recall@K": results_df["recall_pop"].mean(),
        "NDCG": results_df["ndcg_pop"].mean(),
        "Coverage": coverage_pop,
        "Diversity": diversity_pop,
        "Serendipity": serendipity_pop,
        "Context": "Non-personalized popularity baseline"
    },
    {
        "Approach": "Top Reorder Rate",
        "RMSE": rmse_reorder,
        "MAE": mae_reorder,
        "Precision@K": results_df["precision_reorder"].mean(),
        "Recall@K": results_df["recall_reorder"].mean(),
        "NDCG": results_df["ndcg_reorder"].mean(),
        "Coverage": coverage_reorder,
        "Diversity": diversity_reorder,
        "Serendipity": serendipity_reorder,
        "Context": "Ranks products by reorder tendency"
    },
    {
        "Approach": "Weighted Reorder Score",
        "RMSE": rmse_bayesian,
        "MAE": mae_bayesian,
        "Precision@K": results_df["precision_bayesian"].mean(),
        "Recall@K": results_df["recall_bayesian"].mean(),
        "NDCG": results_df["ndcg_bayesian"].mean(),
        "Coverage": coverage_bayesian,
        "Diversity": diversity_bayesian,
        "Serendipity": serendipity_bayesian,
        "Context": "Balances reorder rate and purchase volume"
    }
])

comparison_table = comparison_table.round(4)
comparison_table